# Generated by Django 6.0.3 on 2026-04-10 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri_kompanise', models.CharField(max_length=200, verbose_name='Emri i Kompanisë')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logoja')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Linku i Website-it')),
                ('data_shtimit', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Llogaria e Partnerit')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerët Tanë',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('conditions', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('location_link', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='JobApp.partner')),
            ],
        ),
    ]
