# Generated by Django 6.0.3 on 2026-04-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_job_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='author',
        ),
    ]
