# Generated by Django 6.0.3 on 2026-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0005_cv_aplikim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplikim',
            name='applicant_cv',
        ),
        migrations.AddField(
            model_name='aplikim',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplikim',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplikim',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aplikim',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplikim',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplikim',
            name='description',
            field=models.TextField(verbose_name='Pse jeni ju kandidati i duhur?'),
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
