# Generated by Django 6.0.3 on 2026-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0007_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplikim',
            options={'verbose_name': 'Aplikim', 'verbose_name_plural': 'Aplikime'},
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Tiranë', 'Tiranë'), ('Durrës', 'Durrës'), ('Vlorë', 'Vlorë'), ('Shkodër', 'Shkodër'), ('Fier', 'Fier'), ('Korçë', 'Korçë'), ('Elbasan', 'Elbasan'), ('Berat', 'Berat'), ('Lushnjë', 'Lushnjë'), ('Kavajë', 'Kavajë'), ('Gjirokastër', 'Gjirokastër'), ('Sarandë', 'Sarandë'), ('Lezhë', 'Lezhë'), ('Kukës', 'Kukës')], default='Tiranë', max_length=100),
        ),
    ]
