# Generated by Django 6.0.3 on 2026-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0008_alter_aplikim_options_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Informatikë', 'Informatikë / Teknologji'), ('Ekonomi', 'Ekonomi / Financë'), ('Marketing', 'Marketing / Shitje'), ('Administratë', 'Administratë / Zyrat'), ('Inxhinieri', 'Inxhinieri'), ('Mjekësi', 'Mjekësi / Shëndetësi'), ('Arsim', 'Arsim / Shkencë'), ('Turizëm', 'Turizëm / Hoteleri'), ('Ndërtim', 'Ndërtim'), ('Tjetër', 'Tjetër')], default='Informatikë', max_length=100),
        ),
    ]
